<?php

namespace Rodgermd\ContestNominationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContestNominationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestNominationRepository extends EntityRepository
{
}
