<?php

namespace Rodgermd\ContestNominationsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContestVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestVoteRepository extends EntityRepository
{
  /**
   * Gets last vote in contest
   * @param ContestNomination $contest_nomination
   * @param $ipaddress
   * @return ContestVote|null
   */
  public function getLastContestVote(ContestNomination $contest_nomination, $ipaddress)
  {
    return $this->createQueryBuilder('cv')
      ->innerJoin('cv.contest_member', 'cm')
      ->where('cm.contest_nomination = :nomination')->setParameter('nomination', $contest_nomination->getId())
      ->andWhere('cv.ip = :ip')->setParameter('ip', $ipaddress)
      ->orderBy('cv.created_at', 'desc')
      ->setMaxResults(1)
      ->getQuery()
      ->getOneOrNullResult();
  }
}
